const CONFIG = {
  DEFAULT_TEMPLATE_FOLDER_ID: "",
  DESTINATION_PARENT_FOLDER_ID: "",
  KEYWORD_TO_REPLACE: "TERM",

  MATCH_CASE: true,   // only "TERM", never "term"/"Term"
  WHOLE_WORD: true,   // never touches DETERMINE / MIDTERM / TERMS

  REQUIRE_ORG_LOGIN: true,
  COLLECT_RESPONDER_EMAIL: true,
  LIMIT_ONE_RESPONSE: false,
  PUBLISH_FORMS: true,

  SPAWNED_FORM_RETRIES: 5,
  SPAWNED_FORM_WAIT_MS: 1500,

  MAX_RUNTIME_MS: 4.5 * 60 * 1000,
};

const JOB_KEY = "PENDING_PROVISIONING_JOB_FILE";